// nodejs/src/components/NavBar.vue
<!--Navbar.vue-->
<template>
<b-navbar toggleable="md" type="dark" variant="dark">

  <b-navbar-toggle target="nav_collapse"></b-navbar-toggle>

  <b-navbar-brand href="#">
      <img src="https://students.usask.ca/images/icons/healthy-vegetarian-eating.png" width="30" height="30" class="d-inline-block align-top" alt=""/>
        <strong>My Health Plate</strong>
    </b-navbar-brand>

  <b-collapse is-nav id="nav_collapse">
    <!-- Right aligned nav items -->
    <b-navbar-nav class="ml-auto">
        <b-nav-item href="#">About</b-nav-item>
        <b-nav-item href="#">Contact</b-nav-item>

        <b-nav-item-dropdown right>
            <!-- Using button-content slot -->
            <template slot="button-content">
            <em>User</em>
            </template>
            <b-dropdown-item href="#">Profile</b-dropdown-item>
            <b-dropdown-item href="#">Signout</b-dropdown-item>
        </b-nav-item-dropdown>

        <b-nav-form>
            <b-form-input size="sm" class="mr-sm-2" type="text" placeholder="Search recipes"/>
            <b-button size="sm" class="my-2 my-sm-0 btn-info" type="submit">Search</b-button>
        </b-nav-form>


    </b-navbar-nav>

  </b-collapse>
</b-navbar>
</template>

<script>
export default {
  name: 'NavBar',
  data () {
    return {
    }
  }
}
</script>


<style scoped>

</style>

// angular/src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  scroll(el){
    el.scrollIntoView();
  }

}

<!--Navbar-->
<mdb-navbar SideClass="navbar navbar-expand-lg navbar-dark elegant-color">
           
  <!-- Navbar brand -->
  <logo><a class="navbar-brand" href="#"><img src="https://students.usask.ca/images/icons/healthy-vegetarian-eating.png" width="30" height="30" class="d-inline-block align-top" alt=""/>
    <strong>My Health Plate</strong></a></logo>

  <!-- Collapsible content -->
  <links>

      <!-- Links -->
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
              <a class="nav-link waves-light" mdbWavesEffect href="#about">About<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
              <a class="nav-link waves-light" mdbWavesEffect>Contact</a>
          </li>

          <!-- Dropdown -->
          <li class="nav-item dropdown" dropdown>
              <a dropdownToggle mdbWavesEffect type="button" class="nav-link dropdown-toggle waves-light" mdbWavesEffect>
              Basic dropdown<span class="caret"></span></a>
              <div *dropdownMenu class="dropdown-menu dropdown dropdown-primary" role="menu">
                  <a class="dropdown-item waves-light" mdbWavesEffect href="#">Action</a>
                  <a class="dropdown-item waves-light" mdbWavesEffect href="#">Another action</a>
                  <a class="dropdown-item waves-light" mdbWavesEffect href="#">Something else here</a>
                  <div class="divider dropdown-divider"></div>
                  <a class="dropdown-item waves-light" mdbWavesEffect href="#">Separated link</a>
              </div>
          </li>

      </ul>
      <!-- Links -->

<!-- Search form -->
      <form class="form-inline waves-light" mdbWavesEffect>
          <div class="md-form mt-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Username">
              <input class="form-control mr-sm-2" type="password" placeholder="Password">
          </div>
      </form>
  </links>
  <!-- Collapsible content -->

</mdb-navbar>
<!--/.Navbar-->
